--- !ditz.rubyforge.org,2008-03-06/project 
name: symbol-macrolet
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: symbol-macrolet
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-07-06 09:18:41.995750 Z
    - bowbow99 <bowbow99@gmail.com>
    - created
    - ""
